### ISSUE TITLE
issues with Pusher library

### ISSUE THREAD

**Issue by tgoldenberg** [onfido/jasmine-react-rails#1]
Hi, I am trying to test my React components and am getting an error that "Pusher is not defined." I am trying to either stub the Pusher variable ( the component in getInitialState calls pusher: new Pusher(app-key)), or require the Pusher library, with no success in either approach. Any suggestions? Thank you!

**Comment by tgoldenberg** [comment]
Also, how would I add support for the Jquery library?

**Comment by BlakeTurner** [comment]
Stubbing is definitely the way to go here. Make sure you require your component with `rewire` instead of `require`, then stub Pusher using .**set**. There's a good example of this in the Readme.

If you're looking to test JQuery behaviours, you're probably no longer unit testing your component, so I would recommend something like Capybara for testing that type of browser interaction.

**Comment by tgoldenberg** [comment]
Hmm.. I have a component that has an if/else block with jQuery code in the render function.. Guess I should move that out then? Thanks for the Pusher advice. If you do know of an easy way to include the JQuery library in the tests, please let me know as well. Thank you for this project, it is the easiest way to get started testing React in Rails that I have seen, so far!

**Comment by BlakeTurner** [comment]
Thanks! It definitely still needs a lot of work. That's why issues like this are helpful.

Re: JQuery. I would definitely refactor the JQuery call out of your render method, but that probably still won't solve your problem. Have you tried stubbing out the $ variable using rewire? You could write a simple object to replace your plugin.

```
// Load rewire
var rewire = require("rewire");

// Load the Component module and set component as its own variable
// Note the use of 'rewire' instead of 'require'
var MyComponentModule = rewire(__component_base + '/path/to/my_component');
var MyComponent = MyComponentModule.component;

var dummyJQuery = {
  pluginName: function() {
    return true; // or whatever you need
  }
}

describe('MyComponent', function(){
  var testValue = 'Test Value';

  beforeEach(function(done) {
    MyComponentModule.__set__({
      '$': dummyJQuery
    });
    this.subject = jasmineReact.render(<MyComponent value={testValue} />);
    done();
  });
});
```
